# Generated by Django 2.2 on 2019-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191006_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('fi', 'Fish'), ('ca', 'Cat'), ('bi', 'Bird'), ('ot', 'Other')], default='fi', max_length=120),
        ),
    ]
