# Generated by Django 2.2 on 2019-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191009_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='bird',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fish',
            field=models.BooleanField(default=False),
        ),
    ]
