# Generated by Django 2.2 on 2019-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191010_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('gishes', 'Fish'), ('cats', 'Cat'), ('dogs', 'Dog'), ('birds', 'Bird'), ('featured', 'Featured')], default='gishes', max_length=120),
        ),
    ]
