# Generated by Django 2.2 on 2019-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191010_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('fishes', 'Fish'), ('cats', 'Cat'), ('dogs', 'Dog'), ('birds', 'Bird'), ('featured', 'Featured'), ('accessories', 'Accessories')], default=None, max_length=120),
        ),
    ]
