# Generated by Django 2.2 on 2019-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20191012_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('cats', 'Cat'), ('dogs', 'Dog'), ('birds', 'Bird'), ('featured', 'Featured'), ('fish', 'Fishes'), ('accessories', 'Accessories')], default='cats', max_length=120),
        ),
    ]
