# Generated by Django 2.2 on 2019-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20191012_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field1',
            field=models.CharField(default='navy', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field2',
            field=models.CharField(default='navy', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field3',
            field=models.CharField(default='navy', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field4',
            field=models.CharField(default='navy', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field5',
            field=models.CharField(default='navy', max_length=120, null=True),
        ),
    ]
