# Generated by Django 2.2 on 2019-10-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20191015_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field5',
        ),
    ]
