# Generated by Django 2.2 on 2019-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20191028_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_no',
            field=models.IntegerField(default=91),
        ),
    ]
