# Generated by Django 2.2 on 2019-10-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blilling',
            name='active',
        ),
    ]
