# Generated by Django 2.2 on 2019-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_blilling_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blilling',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
