# Generated by Django 2.2.7 on 2019-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_blilling_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blilling',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
